---
- hosts: all
  gather_facts: false
  connection: local
  collections:
    - junipernetworks.junos
        
  tasks:
    - name: VLAN description
      junos_config:
        lines: 
        - set interfaces ge-0/0/2 description "LAN Connection to Routers"
      register: output
    - debug: var=output
